# minimal values files for testing - enable just what you need and copy required values from staging environment

global:
  defaultNodePool: default-pool
  k8sOpsSecretName: ops
  k8sOpsImage: gcr.io/uumpa123/midburn-k8s
  environmentName: ori
  opsRepoSlug: Midburn/midburn-k8s
  opsRepoBranch: master
  googleProjectId: midbarrn
  projectName: midburn
  enableRootChart: true
  # this is the same for all environments
  # gcloud compute instances describe midburn-k8s-persistent-storage-vm --zone=us-central1-a --format='value(networkInterfaces[0].networkIP)'
  persistentStorageIP: 10.128.0.7

traefik:
  enabled: false
  enableLoadBalancer: false
  profilesHostsRule: ""

spark:
  enabled: true
  enableDeployment: false
  # see Shared / Persistent Storage section in the README to prepare the storage / import existing data
  persistentStorageName: sparkdb

nginx:
  enabled: true
  htpasswdSecretName: nginx-htpasswd

volunteers:
  enabled: false

profiles:
  enabled: false
  # dbImportUrl: gs://midburn-k8s-backups/profiles-db-production-dump-2018-01-16-11-30.sql
  # NO trailing slash!
  # drupalBaseUrl: http://localhost

bi:
  enabled: true
