# minimal values files for testing - enable just what you need and copy required values from staging environment

global:
  k8sOpsSecretName: ops
  k8sOpsImage: gcr.io/uumpa123/midburn-k8s
  environmentName: ori
  opsRepoSlug: Midburn/midburn-k8s
  opsRepoBranch: master
  googleProjectId: midbarrn
  projectName: midburn
  enableRootChart: true
  # this is the same for all environments
  # gcloud compute instances describe midburn-k8s-persistent-storage-vm --zone=us-central1-a --format='value(networkInterfaces[0].networkIP)'
  persistentStorageIP: 10.128.0.7

traefik:
  enabled: true
  enableLoadBalancer: false
  profilesHostsRule: ""
  # campsIndexPath: "/camps-2018/"

spark:
  enabled: true
  enableDeployment: true
  enableSecrets: false

nginx:
  enabled: true
  htpasswdSecretName: nginx-htpasswd

volunteers:
  enabled: true
  enableSecrets: false

profiles:
  enabled: true

bi:
  enabled: true

camps-index:
  enabled: false
  sparkAppSecretName: sparkdb-app
