apiVersion: v1
kind: Service
metadata:
  name: loomio-mailin
spec:
  ports:
  - name: '25'
    port: 25
  selector:
    app: loomio-mailin
  {{ if .Values.enableLoadBalancer }}
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
  {{ end }}
