{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: loomio-mailin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loomio-mailin
    spec:
      containers:
      - name: mailin
        image: loomio/mailin-docker:latest
        ports:
        - containerPort: 25
        resources: {"requests": {"cpu": "50m", "memory": "200Mi"}, "limits": {"memory": "1Gi"}}
        env:
        - name: WEBHOOK_URL
          value: http://loomio:3000/email_processor/
{{ end }}
