{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dreamsdb
spec:
  ports:
  - name: '5432'
    port: 5432
  selector:
    app: dreamsdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dreamsdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dreamsdb
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: dreamsdb
        image: "postgres"
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 20m
        env:
        - name: POSTGRES_USER
          value: dreams
        - name: POSTGRES_DB
          value: dreams
        - name: POSTGRES_PASSWORD
          value: "123456"
{{ end }}
