{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sparkdb
spec:
  ports:
  - name: '3306'
    port: 3306
  selector:
    app: sparkdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sparkdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sparkdb
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: sparkdb
        image: mariadb:10.0
        ports:
        - {containerPort: 3306}
        resources: {{ .Values.sparkDbResources }}
        {{ if .Values.rootSecretName }}
        envFrom:
        # root secret - contains the mysql root password
        - secretRef:
            name: {{ .Values.rootSecretName | quote }}
        # app secret - contains the spark db connection details
        - secretRef:
            name: {{ .Values.appSecretName | quote }}
        {{ else }}
        # default values for insecure environment
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: spark
        - name: MYSQL_USER
          value: spark
        - name: MYSQL_PASSWORD
          value: spark
        {{ end }}
      {{ if .Values.persistentStorageName }}
        volumeMounts:
        - name: sparkdb
          mountPath: /var/lib/mysql
      volumes:
      - name: sparkdb
        nfs:
          path: "/data/{{ .Values.global.environmentName }}/{{ .Values.persistentStorageName }}"
          server: {{ .Values.global.persistentStorageIP | quote }}
      {{ end }}
{{ end }}
