{{ if .Values.enabled }}{{ if .Values.DRUPAL_TICKET_SYNC_EVERY_X_MINUTES }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark-drupal-sync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-drupal-sync
    spec:
      containers:
      - name: spark
        image: {{ .Values.image | default "orihoch/spark:modernize-dockerize" | quote }}
        resources:
          requests:
            cpu: 20m
        envFrom: [{"configMapRef": {"name": "spark"}}]
        env:
        - name: DRUPAL_TICKET_SYNC_EVERY_X_MINUTES
          value: {{ .Values.DRUPAL_TICKET_SYNC_EVERY_X_MINUTES | quote }}
        {{ if .Values.appSecretName }}
        - {"name": "SPARK_DB_DBNAME", "valueFrom": {"secretKeyRef": {"name": {{ .Values.appSecretName | quote }}, "key": "MYSQL_DATABASE"}}}
        - {"name": "SPARK_DB_USER", "valueFrom": {"secretKeyRef": {"name": {{ .Values.appSecretName | quote }}, "key": "MYSQL_USER"}}}
        - {"name": "SPARK_DB_PASSWORD", "valueFrom": {"secretKeyRef": {"name": {{ .Values.appSecretName | quote }}, "key": "MYSQL_PASSWORD"}}}
        {{ else }}
        - {"name": "SPARK_DB_DBNAME", "value": "spark"}
        - {"name": "SPARK_DB_USER", "value": "spark"}
        - {"name": "SPARK_DB_PASSWORD", "value": "spark"}
        {{ end }}
        {{ if .Values.secureMailserverSecretName }}
        - {"name": "SPARK_MAILSERVER_USER", "valueFrom": {"secretKeyRef": {"name": {{ .Values.secureMailserverSecretName | quote }}, "key": "SPARK_MAILSERVER_USER"}}}
        - {"name": "SPARK_MAILSERVER_PASSWORD", "valueFrom": {"secretKeyRef": {"name": {{ .Values.secureMailserverSecretName | quote }}, "key": "SPARK_MAILSERVER_PASSWORD"}}}
        {{ end }}
        {{ if .Values.facebookSecretName }}
        - {"name": "SPARK_FACEBOOK_SECRET", "valueFrom": {"secretKeyRef": {"name": {{ .Values.facebookSecretName | quote }}, "key": "SPARK_FACEBOOK_SECRET"}}}
        {{ end }}
        {{ if .Values.recaptchaSecretName }}
        - {"name": "SPARK_RECAPTCHA_SITEKEY", "valueFrom": {"secretKeyRef": {"name": {{ .Values.recaptchaSecretName | quote }}, "key": "SPARK_RECAPTCHA_SITEKEY"}}}
        - {"name": "SPARK_RECAPTCHA_SECRETKEY", "valueFrom": {"secretKeyRef": {"name": {{ .Values.recaptchaSecretName | quote }}, "key": "SPARK_RECAPTCHA_SECRETKEY"}}}
        {{ end }}
        {{ if .Values.drupalSecretName }}
        - {"name": "DRUPAL_PROFILE_API_PASSWORD", "valueFrom": {"secretKeyRef": {"name": {{ .Values.drupalSecretName | quote }}, "key": "DRUPAL_PROFILE_API_PASSWORD"}}}
        {{ end }}
        - name: SPARK_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: spark-secret-token
              key: SPARK_SECRET_TOKEN
{{ end }}{{ end }}
