{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tickets-sync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tickets-sync
    spec:
      containers:
      - name: sync
        image: orihoch/midburn-k8s-tickets-sync@sha256:16be619b413dca75025a3a1b692b8f6bcb637e5a1726b6012eea6b92c63aee38
        env:
        - name: UPDATE_BATCH_SIZE
          value: "100"
        - name: UPDATE_INTERVAL_SECONDS
          value: "60"
        envFrom:
        - secretRef:
            name: {{ .Values.secretName | quote }}
        resources: {{ .Values.resources }}
{{ end }}
