{{ if .Values.adminer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  selector:
    app: adminer
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
        resources: {{ .Values.adminer.resources }}
{{ end }}
