{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: communitiesdb
spec:
  ports:
    - port: 3306
  selector:
    app: communitiesdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: communities-mysql-pv-claim
  labels:
    app: communitiesdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: communitiesdb
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: communitiesdb
    spec:
      containers:
      - name: communitiesdb
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        resources: {{ .Values.communitiesDbResources }}
        envFrom:
        # root secret - contains the mysql root password
        - secretRef:
            name: {{ .Values.rootSecretName | quote }}
        # app secret - contains the communities db connection details
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appSecretName | quote }}
                key: MYSQL_DB_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appSecretName | quote }}
                key: MYSQL_DB_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appSecretName | quote }}
                key: MYSQL_DB_PASSWORD
        volumeMounts:
        - name: communitiesdb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: communitiesdb-storage
        persistentVolumeClaim:
          claimName: communities-mysql-pv-claim
{{ end }}
