{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: communities
data:
  #### DB configuration ####
  COMMUNITIES_DB_CLIENT: mysql
  COMMUNITIES_DB_HOSTNAME: communitiesdb
  COMMUNITIES_DB_DEBUG: "false"
  {{ if .Values.allowPopulateDB }}
  ALLOW_POPULATE_DB: "yes"
  {{ end }}

  #### App configuration ####
  COMMUNITIES_SERVER_PORT: "3003"
  COMMUNITIES_SERVER_HOSTNAME: localhost
  COMMUNITIES_SERVER_PROTOCOL: http
  COMMUNITIES_SERVER_URL: {{ .Values.serverUrl | quote }}
  COMMUNITIES_RECAPTCHA_IGNORE: "true"
  {{ if .Values.nodeEnv }}
  NODE_ENV: {{ .Values.nodeEnv | quote }}
  {{ end }}

  #### Mail configuration ####
  {{ if .Values.secureMailserverSecretName }}
  COMMUNITIES_MAILSERVER_ENABLE: "true"
  COMMUNITIES_MAILSERVER_SECURE_CONNECTION: "true"
  COMMUNITIES_MAILSERVER_METHOD: SMTP
  COMMUNITIES_MAILSERVER_FROM: {{ .Values.mailserverFrom | quote }}
  COMMUNITIES_MAILSERVER_HOST: {{ .Values.mailserverHost | quote }}
  COMMUNITIES_MAILSERVER_PORT: {{ .Values.mailserverPort | quote }}
  {{ else }}
  COMMUNITIES_MAILSERVER_ENABLE: "false"
  {{ end }}

  # DRUPAL
  {{ if .Values.drupalSecretName }}
  USE_DRUPAL_CACHE: "true"
#  DRUPAL_TICKET_SYNC_EVERY_X_MINUTES: {{ .Values.drupalTicketSyncEveryXMinutes | quote }}
  DRUPAL_PROFILE_API_URL: {{ .Values.drupalProfileApiURL | quote }}
  DRUPAL_PROFILE_API_USER: {{ .Values.drupalProfileApiUser | quote }}
  SKIP_DRUPAL_LOGIN: {{ .Values.drupalSkipLogin | default "" | quote }}
  {{ end }}

  # VOLUNTEERS
  {{ if .Values.volunteersBaseUrl }}
  VOLUNTEERS_BASE_URL: {{ .Values.volunteersBaseUrl | quote }}
  {{ end }}
{{ end }}
